print("The Code Dungeon Commandments")
print("1. Don't be stingy and sniveling")
print("2. Coding must be every saturday")
# im sorry women for this next commandment
print("3. No women in the coding dungeon")
print("4. No cussing in the coding dungeon")
print("5. Do bring your laptop for coding dungeon")
print("6. No dating minors")
print("7. Be kind to others :^)")
print("8. Learn something new every session")
print("9. No music in the coding dungeon")
print("10. Don't get sidetracked")
print("11. We all share one github account")
print("12. No ChatGPT")
print("13. No stealing others codes")
